import Head from "next/head";
import { useRouter } from "next/router";
import React, { useEffect } from "react";

const Landing = () => {
  const getToken =
    typeof window !== "undefined"
      ? JSON.parse(localStorage.getItem("e-book") as any)
      : null;
  const router = useRouter();
  useEffect(() => {
    if (!getToken) {
      router.push("login");
    }
  }, [getToken]);

  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="h-[600px] w-full flex justify-center items-center">
        <h1 className="text-[70px] font-mono"> Hi Landing.! </h1>
      </div>
    </>
  );
};

export default Landing;
