import Card from "@/components/card/card";
import Head from "next/head";
import { useRouter } from "next/router";
import React, { useEffect } from "react";

const Landing = () => {
  const getToken =
    typeof window !== "undefined"
      ? JSON.parse(localStorage.getItem("e-book") as any)
      : null;
  const router = useRouter();
  useEffect(() => {
    if (!getToken) {
      router.push("login");
    }
  }, [getToken]);

  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="wrapper py-[40px] grid grid-cols-12 gap-8">
        <div className="lg:col-span-6 col-span-12">
          <Card
            bade="New"
            desc="Lorem ipsum dolor sit amet consectetur, adipisicing elit. Suscipit, reiciendis?"
            img="/images/book-one.jpg"
            price="30000$"
            title="Book One"
          />
        </div>
        <div className="lg:col-span-6 col-span-12">
          <Card
            bade="New"
            desc="Lorem ipsum dolor sit amet consectetur, adipisicing elit. Suscipit, reiciendis?"
            img="/images/book-one.jpg"
            price="30000$"
            title="Book One"
          />
        </div>
        <div className="lg:col-span-6 col-span-12">
          <Card
            bade="New"
            desc="Lorem ipsum dolor sit amet consectetur, adipisicing elit. Suscipit, reiciendis?"
            img="/images/book-one.jpg"
            price="30000$"
            title="Book One"
          />
        </div>
        <div className="lg:col-span-6 col-span-12">
          <Card
            bade="New"
            desc="Lorem ipsum dolor sit amet consectetur, adipisicing elit. Suscipit, reiciendis?"
            img="/images/book-one.jpg"
            price="30000$"
            title="Book One"
          />
        </div>
      </div>
    </>
  );
};

export default Landing;
